using System.Collections.Generic;
using ICSharpCode.AvalonEdit.CodeCompletion;

namespace EspBrowser
{
  public class LuaCodeCompletion
  {
    bool reset = true;
    IList<ICompletionData> items = new List<ICompletionData>();

    public IList<ICompletionData> Items
    {
      get { return items; }
    }

    public LuaCodeCompletion()
    {
      AddDefaultIntellisense();
    }

    void AddDefaultIntellisense()
    {
      if(reset)
      {
        items = new List<ICompletionData>()
        {
          // Lua keywords
          new LuaCompletionItem("function"),
          new LuaCompletionItem("false"),
          new LuaCompletionItem("for"),
          new LuaCompletionItem("and"),
          new LuaCompletionItem("break"),
          new LuaCompletionItem("else"),
          new LuaCompletionItem("elseif"),
          new LuaCompletionItem("end"),
          new LuaCompletionItem("do"),
          new LuaCompletionItem("if"),
          new LuaCompletionItem("in"),
          new LuaCompletionItem("local"),
          new LuaCompletionItem("nil"),
          new LuaCompletionItem("not"),
          new LuaCompletionItem("or"),
          new LuaCompletionItem("repeat"),
          new LuaCompletionItem("return"),
          new LuaCompletionItem("then"),
          new LuaCompletionItem("true"),
          new LuaCompletionItem("until"),
          new LuaCompletionItem("using"),
          new LuaCompletionItem("while"),

          new LuaCompletionItem("__gc"),
          new LuaCompletionItem("__tostring"),
          new LuaCompletionItem("__add"),
          new LuaCompletionItem("__sub"),
          new LuaCompletionItem("__mul"),
          new LuaCompletionItem("__div"),
          new LuaCompletionItem("__mod"),
          new LuaCompletionItem("__pow"),
          new LuaCompletionItem("__unm"),
          new LuaCompletionItem("__rshift"),
          new LuaCompletionItem("__lshift"),
          new LuaCompletionItem("__bitand"),
          new LuaCompletionItem("__bitor"),
          new LuaCompletionItem("__len"),
          new LuaCompletionItem("__eq"),
          new LuaCompletionItem("__lt"),
          new LuaCompletionItem("__le"),
          new LuaCompletionItem("__call"),
          new LuaCompletionItem("__concat"),
          new LuaCompletionItem("__type"),
          new LuaCompletionItem("__index"),
          new LuaCompletionItem("__newindex"),
                    
          // Used a script to generate this. Just run that script and 
          // then copy/paste the output into here, replacing the current stuff.
          new LuaCompletionItem("string"),
          new LuaCompletionItem("split"),
          new LuaCompletionItem("match"),
          new LuaCompletionItem("gmatch"),
          new LuaCompletionItem("upper"),
          new LuaCompletionItem("gsub"),
          new LuaCompletionItem("format"),
          new LuaCompletionItem("lower"),
          new LuaCompletionItem("sub"),
          new LuaCompletionItem("gfind"),
          new LuaCompletionItem("find"),
          new LuaCompletionItem("char"),
          new LuaCompletionItem("dump"),
          new LuaCompletionItem("undump"),
          new LuaCompletionItem("reverse"),
          new LuaCompletionItem("byte"),
          new LuaCompletionItem("strmatch"),
          new LuaCompletionItem("len"),
          new LuaCompletionItem("rep"),

          new LuaCompletionItem("xpcall"),
          new LuaCompletionItem("package"),
          new LuaCompletionItem("preload"),
          new LuaCompletionItem("loadlib"),
          new LuaCompletionItem("loaded"),
          new LuaCompletionItem("loaders"),
          new LuaCompletionItem("cpath"),
          new LuaCompletionItem("config"),
          new LuaCompletionItem("path"),
          new LuaCompletionItem("seeall"),

          new LuaCompletionItem("tostring"),
          new LuaCompletionItem("print"),
          new LuaCompletionItem("os"),
          new LuaCompletionItem("exit"),
          new LuaCompletionItem("setlocale"),
          new LuaCompletionItem("date"),
          new LuaCompletionItem("getenv"),
          new LuaCompletionItem("difftime"),
          new LuaCompletionItem("remove"),
          new LuaCompletionItem("time"),
          new LuaCompletionItem("clock"),
          new LuaCompletionItem("tmpname"),
          new LuaCompletionItem("rename"),
          new LuaCompletionItem("execute"),

          new LuaCompletionItem("unpack"),
          new LuaCompletionItem("scanned"),

          new LuaCompletionItem("set_global_mt"),
          new LuaCompletionItem("require"),
          new LuaCompletionItem("getfenv"),
          new LuaCompletionItem("DEBUG"),
          new LuaCompletionItem("setmetatable"),
          new LuaCompletionItem("next"),
          new LuaCompletionItem("luanet"),
          new LuaCompletionItem("assert"),
          new LuaCompletionItem("clr"),
          new LuaCompletionItem("call"),
          new LuaCompletionItem("create"),
          new LuaCompletionItem("ns"),
          new LuaCompletionItem("usingns"),
          new LuaCompletionItem("getns"),
          new LuaCompletionItem("load"),
          new LuaCompletionItem("import"),

          new LuaCompletionItem("tonumber"),
          new LuaCompletionItem("newproxy"),
          new LuaCompletionItem("io"),
          new LuaCompletionItem("lines"),
          new LuaCompletionItem("write"),
          new LuaCompletionItem("close"),
          new LuaCompletionItem("flush"),
          new LuaCompletionItem("open"),
          new LuaCompletionItem("output"),
          new LuaCompletionItem("type"),
          new LuaCompletionItem("read"),
          new LuaCompletionItem("stderr"),
          new LuaCompletionItem("stdin"),
          new LuaCompletionItem("input"),
          new LuaCompletionItem("stdout"),
          new LuaCompletionItem("popen"),
          new LuaCompletionItem("tmpfile"),

          new LuaCompletionItem("rawequal"),
          new LuaCompletionItem("Lua"),
          new LuaCompletionItem("CLR"),
          new LuaCompletionItem("Clr"),
          new LuaCompletionItem("Parser"),

          new LuaCompletionItem("collectgarbage"),
          new LuaCompletionItem("getmetatable"),
          new LuaCompletionItem("set"),
          new LuaCompletionItem("sleep"),
          new LuaCompletionItem("rawtype"),
          new LuaCompletionItem("System"),

          new LuaCompletionItem("_WORKDIR"),
          new LuaCompletionItem("rawset"),
          new LuaCompletionItem("bit32"),
          new LuaCompletionItem("band"),
          new LuaCompletionItem("extract"),
          new LuaCompletionItem("bor"),
          new LuaCompletionItem("bnot"),
          new LuaCompletionItem("arshift"),
          new LuaCompletionItem("rshift"),
          new LuaCompletionItem("rrotate"),
          new LuaCompletionItem("replace"),
          new LuaCompletionItem("lshift"),
          new LuaCompletionItem("lrotate"),
          new LuaCompletionItem("btest"),
          new LuaCompletionItem("bxor"),

          new LuaCompletionItem("bit"),

          new LuaCompletionItem("debug"),
          new LuaCompletionItem("getupvalue"),
          new LuaCompletionItem("sethook"),
          new LuaCompletionItem("gethook"),
          new LuaCompletionItem("setlocal"),
          new LuaCompletionItem("traceback"),
          new LuaCompletionItem("setfenv"),
          new LuaCompletionItem("getinfo"),
          new LuaCompletionItem("setupvalue"),
          new LuaCompletionItem("getlocal"),
          new LuaCompletionItem("getregistry"),

          new LuaCompletionItem("module"),
          new LuaCompletionItem("table"),
          new LuaCompletionItem("getn"),
          new LuaCompletionItem("cat"),
          new LuaCompletionItem("icat"),
          new LuaCompletionItem("isub"),
          new LuaCompletionItem("transpose"),
          new LuaCompletionItem("iall"),
          new LuaCompletionItem("izip"),
          new LuaCompletionItem("maxn"),
          new LuaCompletionItem("concat"),
          new LuaCompletionItem("irev"),
          new LuaCompletionItem("shallow_copy"),
          new LuaCompletionItem("iforeach"),
          new LuaCompletionItem("tolookup"),
          new LuaCompletionItem("foreachi"),
          new LuaCompletionItem("foreach"),
          new LuaCompletionItem("sort"),
          new LuaCompletionItem("ifold"),
          new LuaCompletionItem("invert"),
          new LuaCompletionItem("ifilter"),
          new LuaCompletionItem("iany"),
          new LuaCompletionItem("pack"),
          new LuaCompletionItem("imap"),
          new LuaCompletionItem("deep_copy"),
          new LuaCompletionItem("range"),
          new LuaCompletionItem("override"),
          new LuaCompletionItem("setn"),
          new LuaCompletionItem("removeitem"),
          new LuaCompletionItem("insert"),
          new LuaCompletionItem("iflatten"),

          new LuaCompletionItem("math"),
          new LuaCompletionItem("sinh"),
          new LuaCompletionItem("log"),
          new LuaCompletionItem("max"),
          new LuaCompletionItem("acos"),
          new LuaCompletionItem("huge"),
          new LuaCompletionItem("ldexp"),
          new LuaCompletionItem("pi"),
          new LuaCompletionItem("cos"),
          new LuaCompletionItem("tanh"),
          new LuaCompletionItem("pow"),
          new LuaCompletionItem("deg"),
          new LuaCompletionItem("tan"),
          new LuaCompletionItem("cosh"),
          new LuaCompletionItem("round"),
          new LuaCompletionItem("random"),
          new LuaCompletionItem("randomseed"),
          new LuaCompletionItem("frexp"),
          new LuaCompletionItem("ceil"),
          new LuaCompletionItem("floor"),
          new LuaCompletionItem("rad"),
          new LuaCompletionItem("abs"),
          new LuaCompletionItem("sqrt"),
          new LuaCompletionItem("modf"),
          new LuaCompletionItem("asin"),
          new LuaCompletionItem("min"),
          new LuaCompletionItem("mod"),
          new LuaCompletionItem("fmod"),
          new LuaCompletionItem("log10"),
          new LuaCompletionItem("atan2"),
          new LuaCompletionItem("exp"),
          new LuaCompletionItem("sin"),
          new LuaCompletionItem("atan"),

          new LuaCompletionItem("coroutine"),
          new LuaCompletionItem("resume"),
          new LuaCompletionItem("yield"),
          new LuaCompletionItem("status"),
          new LuaCompletionItem("wrap"),
          new LuaCompletionItem("running"),

          new LuaCompletionItem("pcall"),
          new LuaCompletionItem("SharpLua"),

          new LuaCompletionItem("pairs"),
          new LuaCompletionItem("ipairs"),
          new LuaCompletionItem("_G"),
          new LuaCompletionItem("select"),
          new LuaCompletionItem("gcinfo"),
          new LuaCompletionItem("rawget"),
          new LuaCompletionItem("loadstring"),
          new LuaCompletionItem("_VERSION"),
          new LuaCompletionItem("wait"),
          new LuaCompletionItem("dofile"),
          new LuaCompletionItem("error"),
          new LuaCompletionItem("loadfile"),

          // Lua modules
          new LuaModuleCompletionItem("alien"),
          new LuaModuleCompletionItem("json"),
          new LuaModuleCompletionItem("leg"),
          new LuaModuleCompletionItem("lpeg"),
          new LuaModuleCompletionItem("cosmo"),
          new LuaModuleCompletionItem("logging"),
          new LuaModuleCompletionItem("loop"),
          new LuaModuleCompletionItem("luadoc"),
          new LuaModuleCompletionItem("luaidl"),
          new LuaModuleCompletionItem("luarocks"),
          new LuaModuleCompletionItem("lxp"),
          new LuaModuleCompletionItem("lxsh"),
          new LuaModuleCompletionItem("metalua"),
          new LuaModuleCompletionItem("oil"),
          new LuaModuleCompletionItem("pl"),
          new LuaModuleCompletionItem("socket"),
          new LuaModuleCompletionItem("vstruct"),
          new LuaModuleCompletionItem("alt_getopt"),
          new LuaModuleCompletionItem("get_opt"),
          new LuaModuleCompletionItem("getopt"),
          new LuaModuleCompletionItem("base"),
          new LuaModuleCompletionItem("classlib"),
          new LuaModuleCompletionItem("cliargs"),
          new LuaModuleCompletionItem("CLRForm"),
          new LuaModuleCompletionItem("CLRPackage"),
          new LuaModuleCompletionItem("copas"),
          new LuaModuleCompletionItem("coxpcall"),
          new LuaModuleCompletionItem("date"),
          new LuaModuleCompletionItem("date2"),
          new LuaModuleCompletionItem("debug_ext"),
          new LuaModuleCompletionItem("debug_init"),
          new LuaModuleCompletionItem("fstable"),
          new LuaModuleCompletionItem("idl2lua"),
          new LuaModuleCompletionItem("ilua"),
          new LuaModuleCompletionItem("io_ext"),
          new LuaModuleCompletionItem("lanes"),
          new LuaModuleCompletionItem("lar"),
          new LuaModuleCompletionItem("lcs"),
          new LuaModuleCompletionItem("lemock"),
          new LuaModuleCompletionItem("list"),
          new LuaModuleCompletionItem("luaunit"),
          new LuaModuleCompletionItem("LuaXml"),
          new LuaModuleCompletionItem("lunit"),
          new LuaModuleCompletionItem("markdown"),
          new LuaModuleCompletionItem("math_ext"),
          new LuaModuleCompletionItem("mbox"),
          new LuaModuleCompletionItem("md5"),
          new LuaModuleCompletionItem("mime"),
          new LuaModuleCompletionItem("object"),
          new LuaModuleCompletionItem("oil"),
          new LuaModuleCompletionItem("package_ext"),
          new LuaModuleCompletionItem("parser"),
          new LuaModuleCompletionItem("posix"),
          new LuaModuleCompletionItem("lposix"),
          new LuaModuleCompletionItem("posix_ext"),
          new LuaModuleCompletionItem("precompiler"),
          new LuaModuleCompletionItem("preloader"),
          new LuaModuleCompletionItem("re"),
          new LuaModuleCompletionItem("rex"),
          new LuaModuleCompletionItem("serialize"),
          new LuaModuleCompletionItem("set"),
          new LuaModuleCompletionItem("stable"),
          new LuaModuleCompletionItem("std"),
          new LuaModuleCompletionItem("strict"),
          new LuaModuleCompletionItem("string_ext"),
          new LuaModuleCompletionItem("table_ext"),
          new LuaModuleCompletionItem("tar"),
          new LuaModuleCompletionItem("unclasslib"),
          new LuaModuleCompletionItem("tree"),
          new LuaModuleCompletionItem("xml"),
          new LuaModuleCompletionItem("luasql"),
          new LuaModuleCompletionItem("md5"),
          new LuaModuleCompletionItem("base64"),
          new LuaModuleCompletionItem("bit"),
          new LuaModuleCompletionItem("cd"),
          new LuaModuleCompletionItem("cdcairo"),
          new LuaModuleCompletionItem("cdcontextplus"),
          new LuaModuleCompletionItem("cdgdk"),
          new LuaModuleCompletionItem("cdgl"),
          new LuaModuleCompletionItem("cdlua51"),
          new LuaModuleCompletionItem("cdluacairo51"),
          new LuaModuleCompletionItem("cdluacontextplus51"),
          new LuaModuleCompletionItem("cdluagl51"),
          new LuaModuleCompletionItem("cdluaim51"),
          new LuaModuleCompletionItem("cdluapdf51"),
          new LuaModuleCompletionItem("cdpdf"),
          new LuaModuleCompletionItem("des56"),
          new LuaModuleCompletionItem("ex"),
          new LuaModuleCompletionItem("freetype6"),
          new LuaModuleCompletionItem("typical"),
          new LuaModuleCompletionItem("ftgl"),
          new LuaModuleCompletionItem("gd"),
          new LuaModuleCompletionItem("gzio"),
          new LuaModuleCompletionItem("im"),
          new LuaModuleCompletionItem("im_avi"),
          new LuaModuleCompletionItem("im_capture"),
          new LuaModuleCompletionItem("im_fftw"),
          new LuaModuleCompletionItem("im_jp2"),
          new LuaModuleCompletionItem("im_process"),
          new LuaModuleCompletionItem("im_wmv"),
          new LuaModuleCompletionItem("imlua_avi51"),
          new LuaModuleCompletionItem("imlua_capture51"),
          new LuaModuleCompletionItem("imlua_fftw51"),
          new LuaModuleCompletionItem("imlua_jp251"),
          new LuaModuleCompletionItem("imlua_process51"),
          new LuaModuleCompletionItem("imlua_wmv51"),
          new LuaModuleCompletionItem("imlua51"),
          new LuaModuleCompletionItem("iup"),
          new LuaModuleCompletionItem("iup_pplot"),
          new LuaModuleCompletionItem("jpeg62"),
          new LuaModuleCompletionItem("lfs"),
          new LuaModuleCompletionItem("libcurl"),
          new LuaModuleCompletionItem("libexpat"),
          new LuaModuleCompletionItem("libgcrypt"),
          new LuaModuleCompletionItem("libgd2"),
          new LuaModuleCompletionItem("libgnutils"),
          new LuaModuleCompletionItem("libgpg_error"),
          new LuaModuleCompletionItem("liibiconv2"),
          new LuaModuleCompletionItem("libintl-8"),
          new LuaModuleCompletionItem("libmysql"),
          new LuaModuleCompletionItem("libpng13"),
          new LuaModuleCompletionItem("libz"),
          new LuaModuleCompletionItem("lpeg_0_10_2-lpeg"),
          new LuaModuleCompletionItem("lua51-lanes"),
          new LuaModuleCompletionItem("luacom"),
          new LuaModuleCompletionItem("luacurl"),
          new LuaModuleCompletionItem("luagl"),
          new LuaModuleCompletionItem("luaglu"),
          new LuaModuleCompletionItem("luanet"),
          new LuaModuleCompletionItem("luars232"),
          new LuaModuleCompletionItem("LuaXML_lib"),
          new LuaModuleCompletionItem("pack"),
          new LuaModuleCompletionItem("pcre"),
          new LuaModuleCompletionItem("pdflib"),
          new LuaModuleCompletionItem("profiler"),
          new LuaModuleCompletionItem("rex_pcre"),
          new LuaModuleCompletionItem("rex_spencer"),
          new LuaModuleCompletionItem("rings"),
          new LuaModuleCompletionItem("rxspencer"),
          new LuaModuleCompletionItem("task"),
          new LuaModuleCompletionItem("w32"),
          new LuaModuleCompletionItem("wx"),
          new LuaModuleCompletionItem("wxmsw28_gl_vc"),
          new LuaModuleCompletionItem("wxmsw28_stc_vc"),
          new LuaModuleCompletionItem("wxmsw28_vc"),
          new LuaModuleCompletionItem("xpm4"),
          new LuaModuleCompletionItem("zip"),
          new LuaModuleCompletionItem("zlib1"),
          new LuaModuleCompletionItem("LuLu"),
          new LuaModuleCompletionItem("yeuliang"),
          new LuaModuleCompletionItem("luaparse"),
          new LuaModuleCompletionItem("lua-inspect")
        };

        reset = false;
      }
    }
  }
}
