//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EspBrowser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EspBrowser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moravcik@mdk.sk.
        /// </summary>
        public static string About_Email {
            get {
                return ResourceManager.GetString("About_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mailto:moravcik@mdk.sk?subject=ESP%20Browser%20{0}.
        /// </summary>
        public static string About_EmailUrl {
            get {
                return ResourceManager.GetString("About_EmailUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESPlorer.
        /// </summary>
        public static string About_ESPlorer {
            get {
                return ResourceManager.GetString("About_ESPlorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://esp8266.ru/esplorer/.
        /// </summary>
        public static string About_ESPlorerUrl {
            get {
                return ResourceManager.GetString("About_ESPlorerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string About_GitHub {
            get {
                return ResourceManager.GetString("About_GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/patrikmor/EspBrowser.
        /// </summary>
        public static string About_GitHubUrl {
            get {
                return ResourceManager.GetString("About_GitHubUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .lua.
        /// </summary>
        public static string Document_DefaultExtension {
            get {
                return ResourceManager.GetString("Document_DefaultExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua files (*.lua)|*.lua|All files (*.*)|*.*.
        /// </summary>
        public static string Document_DefaultFilterLua {
            get {
                return ResourceManager.GetString("Document_DefaultFilterLua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua files (*.lua,*.lc)|*.lua;*.lc|All files (*.*)|*.*.
        /// </summary>
        public static string Document_DefaultFilterLuaLc {
            get {
                return ResourceManager.GetString("Document_DefaultFilterLuaLc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to script.
        /// </summary>
        public static string Document_DefaultName {
            get {
                return ResourceManager.GetString("Document_DefaultName", resourceCulture);
            }
        }
    }
}
